// FontAwesome configuration - must be imported before any FA components
import { config, library } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import {
  faFileAlt,
  faMagnifyingGlass,
  faArrowRight,
  faArrowLeft,
  faShield,
  faCamera,
  faHashtag,
  faBullhorn,
  faBars,
  faXmark,
  faCopy,
  faCheck,
  faCheckCircle,
  faThumbsUp,
  faCloudArrowUp,
  faSpinner,
  faFile,
  faImage,
  faExternalLink,
  faLock,
  faTriangleExclamation,
  faShareNodes,
  faEnvelope,
  faClock,
  faUsers,
  faCircleExclamation,
  faGavel,
  faScaleBalanced,
  faHandshake,
  faUserShield,
  faEye,
  faBan,
  faCircleInfo,
  faPaperPlane,
  faCommentDots,
  faArrowUpFromBracket,
  faMedal,
  faRankingStar,
  faChartLine,
  faMobileScreenButton,
  faCartShopping,
  faBuildingColumns,
  faMotorcycle,
  faShieldHalved,
  faBolt,
  faBoxOpen,
  faGraduationCap,
  faHospital,
  faHouseChimney,
  faEllipsis,
  faChevronDown,
  faChevronUp,
  faQuoteLeft,
  faGlobe,
  faRetweet,
  faHeart,
  faUpRightFromSquare,
  faChevronLeft,
  faChevronRight,
  faExpand,
} from '@fortawesome/free-solid-svg-icons';
import {
  faFileLines,
  faCircleCheck,
  faComment,
  faHeart as faHeartRegular,
} from '@fortawesome/free-regular-svg-icons';
import {
  faTwitter,
  faWhatsapp,
  faFacebook,
  faInstagram,
  faXTwitter,
} from '@fortawesome/free-brands-svg-icons';

// Prevent FA from auto-adding CSS (we import it manually above)
config.autoAddCss = false;

// Add all icons to library for global use
library.add(
  faFileAlt, faMagnifyingGlass, faArrowRight, faArrowLeft,
  faShield, faCamera, faHashtag, faBullhorn,
  faBars, faXmark, faCopy, faCheck, faCheckCircle,
  faThumbsUp, faCloudArrowUp, faSpinner, faFile, faImage,
  faExternalLink, faLock, faTriangleExclamation,
  faShareNodes, faEnvelope, faClock, faUsers,
  faCircleExclamation, faGavel, faScaleBalanced,
  faHandshake, faUserShield, faEye, faBan, faCircleInfo,
  faPaperPlane, faCommentDots, faArrowUpFromBracket,
  faMedal, faRankingStar, faChartLine,
  faMobileScreenButton, faCartShopping, faBuildingColumns,
  faMotorcycle, faShieldHalved, faBolt, faBoxOpen,
  faGraduationCap, faHospital, faHouseChimney, faEllipsis,
  faChevronDown, faChevronUp, faQuoteLeft, faGlobe,
  faRetweet, faHeart, faUpRightFromSquare,
  faChevronLeft, faChevronRight, faExpand,
  faFileLines, faCircleCheck, faComment, faHeartRegular,
  faTwitter, faWhatsapp, faFacebook, faInstagram, faXTwitter,
);

export {};
