import type { SocialPost } from '@/components/ui/SocialComplaintCard';

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// REAL CONSUMER COMPLAINT DATA - FRESH 2026 UPDATE
// Based on actual issues reported on social media & consumer forums
// Sources: NCH, ConsumerComplaints.in, Twitter/X, Reddit India
// Aligned with late 2025/early 2026 regulatory notices and consumer developments.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const SOCIAL_COMPLAINTS: SocialPost[] = [

  // ═══════════════════════════════════════════════════════════
  //  E-COMMERCE
  // ═══════════════════════════════════════════════════════════

  // ── FLIPKART ──────────────────────────────────────────────
  {
    id: 'sc-001',
    username: 'priyasharma_del',
    displayName: 'Priya Sharma',
    avatarColor: '#E91E63',
    platform: 'twitter',
    company: 'Flipkart',
    companyColor: '#2874F0',
    category: 'e-commerce',
    text: 'Ordered a laptop from @Flipkart during the promotional sale. Received an empty box containing only bubble wrap. Raised a ticket immediately with unboxing video proof, but it has been stuck in "investigation" for 3 weeks now. Denied a replacement. Order ID: OD4291******. Extremely frustrated. NCH Grievance ID: 620****. ₹54,999 blocked.',
    date: 'May 21, 2026',
    likes: 3420,
    shares: 1890,
    comments: 456,
    meTooCount: 892,
    sourceUrl: 'https://x.com/search?q=flipkart%20empty%20box%20complaint&src=typed_query&f=live',
  },
  {
    id: 'sc-013',
    username: 'deepak.returns',
    displayName: 'Deepak Mehra',
    avatarColor: '#3F51B5',
    platform: 'twitter',
    company: 'Flipkart',
    companyColor: '#2874F0',
    category: 'e-commerce',
    text: 'My return pickup for a defective Smart TV was approved by @Flipkart 12 days ago, but the courier partner (Ekart) hasn\'t turned up. The pickup is rescheduled automatically every night with a message "Customer was not available," which is a blatant lie as my family stays home all day. Customer service says they cannot manually override courier updates. Return window closing! #FlipkartFail',
    date: 'May 21, 2026',
    likes: 1800,
    shares: 920,
    comments: 230,
    meTooCount: 1240,
    sourceUrl: 'https://x.com/search?q=flipkart%20return%20pickup%20not%20coming&src=typed_query&f=live',
  },
  {
    id: 'sc-014',
    username: 'swati.online',
    displayName: 'Swati Agarwal',
    avatarColor: '#FF5722',
    platform: 'facebook',
    company: 'Flipkart',
    companyColor: '#2874F0',
    category: 'e-commerce',
    text: 'Very concerned about e-commerce platforms evading responsibility. Just read the Central Consumer Protection Authority (CCPA) notice issued on May 16, 2026, against Flipkart and others for selling hazardous unregistered chemical weed killers (Cyclosinone) online. The platforms claim they are merely "passive intermediaries," but selling illegal toxic chemicals directly affects public safety. Need stricter enforcement of the Consumer Protection Rules, 2020.',
    date: 'May 21, 2026',
    likes: 2400,
    shares: 1100,
    comments: 340,
    meTooCount: 670,
    sourceUrl: 'https://www.consumercomplaints.in/flipkart-b102/',
  },

  // ── AMAZON INDIA ──────────────────────────────────────────
  {
    id: 'sc-002',
    username: 'rahul.tech.reviews',
    displayName: 'Rahul Verma',
    avatarColor: '#FF9800',
    platform: 'facebook',
    company: 'Amazon India',
    companyColor: '#FF9900',
    category: 'e-commerce',
    text: 'Amazon India delivered a clearly refurbished phone instead of a new one. The box seal was tampered with and the screen had minor fingerprints. When I tried to initiate a return on the same day, the portal blocked it saying "this item is only eligible for replacement." Getting the runaround from their automated chatbot support which keeps closing the chat. ₹32,999 wasted unless customer support resolves this. NCH reference registered.',
    date: 'May 21, 2026',
    likes: 2100,
    shares: 980,
    comments: 312,
    meTooCount: 560,
    sourceUrl: 'https://www.consumercomplaints.in/amazon-india-b163/',
  },
  {
    id: 'sc-015',
    username: 'neeraj_prime',
    displayName: 'Neeraj Kumar',
    avatarColor: '#795548',
    platform: 'twitter',
    company: 'Amazon India',
    companyColor: '#FF9900',
    category: 'e-commerce',
    text: 'Predatory auto-renewals on @AmazonIN! My Prime membership was auto-debited at ₹1,499 even though I specifically disabled auto-renewal in my account settings last month. Support agent says "cancellation request was not fully processed by the payment gateway." This is a classic dark pattern designed to lock in consumer funds. Bank chargeback initiated. ASCI must mandate strict OTP confirmation for all subscription renewals.',
    date: 'May 21, 2026',
    likes: 4200,
    shares: 2100,
    comments: 560,
    meTooCount: 1890,
    sourceUrl: 'https://x.com/search?q=amazon%20prime%20auto%20renewed%20cancelled&src=typed_query&f=live',
  },

  // ── MEESHO ────────────────────────────────────────────────
  {
    id: 'sc-007',
    username: 'meera_tech',
    displayName: 'Meera Reddy',
    avatarColor: '#7B1FA2',
    platform: 'twitter',
    company: 'Meesho',
    companyColor: '#570A57',
    category: 'e-commerce',
    text: 'Extremely disappointed with @Meesho_Official. Received a synthetic polyester outfit when the listing explicitly claimed "100% Premium Khadi Cotton." Raised return request, but it was rejected stating "the delivered product matches the description of the order." The fabric difference is visible to the naked eye. No option to appeal or upload unboxing videos on their basic support UI. Lost ₹899. Misleading advertisements are a serious violation under the Consumer Protection Act.',
    date: 'May 21, 2026',
    likes: 2800,
    shares: 1400,
    comments: 445,
    meTooCount: 2100,
    sourceUrl: 'https://x.com/search?q=meesho%20wrong%20product%20return%20rejected&src=typed_query&f=live',
  },

  // ── MYNTRA ────────────────────────────────────────────────
  {
    id: 'sc-021',
    username: 'sneha.fashion',
    displayName: 'Sneha Chatterjee',
    avatarColor: '#AD1457',
    platform: 'instagram',
    company: 'Myntra',
    companyColor: '#FF3E6C',
    category: 'e-commerce',
    text: 'Myntra warehouse quality check issues are getting out of hand. Returned a pair of shoes that arrived with a minor tear. The pickup agent verified it, but 3 days later, the app shows "Refund Rejected: Item failed warehouse quality inspection because of a tear." They are blaming ME for the defect that the product arrived with! I have the unboxing video, yet customer support refuses to review it. ₹4,200 stuck. Never shopping here again.',
    date: 'May 21, 2026',
    likes: 3900,
    shares: 1800,
    comments: 560,
    meTooCount: 890,
    sourceUrl: 'https://www.consumercomplaints.in/myntra-b117/',
  },

  // ── JIOMART ───────────────────────────────────────────────
  {
    id: 'sc-009',
    username: 'divya.jio.issue',
    displayName: 'Divya Nair',
    avatarColor: '#C62828',
    platform: 'instagram',
    company: 'JioMart',
    companyColor: '#0A3A7D',
    category: 'e-commerce',
    text: 'Ordered fresh groceries and dairy from JioMart. The organic milk carton delivered was already 3 days past its expiration date and the bread had visible green mold. JioMart app says the refund is "approved" but the refund amount has not hit my bank account for over two weeks now. In-app customer executive just copy-pastes "technical transaction glitch, please wait 7-10 working days." Absolute health hazard and financial negligence!',
    date: 'May 21, 2026',
    likes: 3200,
    shares: 1600,
    comments: 520,
    meTooCount: 450,
    sourceUrl: 'https://www.consumercomplaints.in/jiomart-b181/',
  },

  // ── RELIANCE DIGITAL ──────────────────────────────────────
  {
    id: 'sc-027',
    username: 'mohan.tech',
    displayName: 'Mohan Pillai',
    avatarColor: '#01579B',
    platform: 'facebook',
    company: 'Reliance Digital',
    companyColor: '#003B7A',
    category: 'e-commerce',
    text: 'Reliance Digital sold me an "All-Inclusive ResQ Extended Warranty" for my washing machine for ₹3,999. Now that the drum bearing is damaged and making extreme noise, their service team is refusing to cover it, citing a tiny clause in the terms excluding "wear and tear of rotating parts." What is the point of an extended warranty if standard usage parts are excluded? This is deceptive marketing of support products. Demanding a full warranty fee refund.',
    date: 'May 21, 2026',
    likes: 2400,
    shares: 1100,
    comments: 340,
    meTooCount: 560,
    sourceUrl: 'https://www.consumercomplaints.in/reliance-digital-b155/',
  },

  // ── BIGBASKET ─────────────────────────────────────────────
  {
    id: 'sc-026',
    username: 'geeta.grocery',
    displayName: 'Geeta Menon',
    avatarColor: '#00796B',
    platform: 'instagram',
    company: 'BigBasket',
    companyColor: '#8CC53F',
    category: 'e-commerce',
    text: 'BigBasket\'s default "allow substitutes" feature is a forced upselling tactic. I ordered basic Tur Dal at ₹140/kg, but they automatically substituted it with an organic version costing ₹240/kg, charging me the difference without any manual option to reject substitutions during delivery. Customer care refused to refund the difference of ₹100, stating the substitute was of "comparable weight." Underhanded pricing policies!',
    date: 'May 21, 2026',
    likes: 2900,
    shares: 1300,
    comments: 410,
    meTooCount: 1100,
    sourceUrl: 'https://www.consumercomplaints.in/bigbasket-b140/',
  },

  // ═══════════════════════════════════════════════════════════
  //  FOOD DELIVERY
  // ═══════════════════════════════════════════════════════════

  // ── ZOMATO ────────────────────────────────────────────────
  {
    id: 'sc-004',
    username: 'neha.foodie.blr',
    displayName: 'Neha Krishnan',
    avatarColor: '#E91E63',
    platform: 'instagram',
    company: 'Zomato',
    companyColor: '#E23744',
    category: 'food-delivery',
    text: 'Extremely unsafe! Found a sharp metal staple pin embedded in my paneer tikka ordered from Zomato. This could have easily caused internal organ damage to my child. When escalated, Zomato support offered a measly ₹200 wallet coupon as "compensation" and refused to take action against the restaurant. The kitchen is still operating. Filed an official complaint on the FSSAI Food Safety Connect portal. Absolute disregard for customer safety!',
    date: 'May 21, 2026',
    likes: 15600,
    shares: 7800,
    comments: 2340,
    meTooCount: 890,
    sourceUrl: 'https://x.com/search?q=zomato%20foreign%20object%20food&src=typed_query&f=live',
  },
  {
    id: 'sc-017',
    username: 'amit.foodlover',
    displayName: 'Amit Tiwari',
    avatarColor: '#F44336',
    platform: 'twitter',
    company: 'Zomato',
    companyColor: '#E23744',
    category: 'food-delivery',
    text: '@zomato Delivery partner marked my food package as delivered, but when I opened the door, nothing was there. Check of my building CCTV footage shows the rider arriving, clicking a photo of the food box outside my door to upload, and immediately taking the bag back with him! When I raised this, Zomato refused a refund saying "order was verified at your geo-location." This is fraud. NCH Grievance ID: Z-60****.',
    date: 'May 21, 2026',
    likes: 6700,
    shares: 3200,
    comments: 890,
    meTooCount: 1200,
    sourceUrl: 'https://x.com/search?q=zomato%20delivery%20partner%20ate%20food&src=typed_query&f=live',
  },
  {
    id: 'sc-040',
    username: 'ritu.delhi',
    displayName: 'Ritu Kapoor',
    avatarColor: '#E64A19',
    platform: 'twitter',
    company: 'Zomato',
    companyColor: '#E23744',
    category: 'food-delivery',
    text: '@zomato charging ₹10 "platform fee" + ₹45 delivery fee + ₹30 surge charge + ₹20 packaging fee. That is ₹105 in service fees on a ₹180 food order! That\'s a whopping 58% markup in hidden costs. Why does the packaging cost ₹20 when the restaurant uses basic plastic bags? The CCPA needs to clamp down on these excessive, deceptive aggregator fees. Consumers are being outright looted.',
    date: 'May 21, 2026',
    likes: 8900,
    shares: 4100,
    comments: 1320,
    meTooCount: 4500,
    sourceUrl: 'https://x.com/search?q=zomato%20platform%20fee%20hidden%20charges&src=typed_query&f=live',
  },

  // ── SWIGGY ────────────────────────────────────────────────
  {
    id: 'sc-010',
    username: 'rohan_bangalore',
    displayName: 'Rohan Desai',
    avatarColor: '#FF6F00',
    platform: 'twitter',
    company: 'Swiggy',
    companyColor: '#FC8019',
    category: 'food-delivery',
    text: 'Ongoing CCPA investigation against @Swiggy and Zomato regarding steep cancellation fees in 2026 is fully justified. Swiggy charged me a cancellation fee of 100% of my order value (₹850) when I requested cancellation just 60 seconds after placing the order, before the restaurant had even confirmed or started preparing the food. This is an unfair trade practice. Aggregators cannot pocket consumer money for zero services rendered.',
    date: 'May 21, 2026',
    likes: 7200,
    shares: 3600,
    comments: 1100,
    meTooCount: 1670,
    sourceUrl: 'https://x.com/search?q=swiggy%20marked%20delivered%20not%20received&src=typed_query&f=live',
  },
  {
    id: 'sc-020',
    username: 'lakshmi.food',
    displayName: 'Lakshmi Iyer',
    avatarColor: '#E65100',
    platform: 'instagram',
    company: 'Swiggy',
    companyColor: '#FC8019',
    category: 'food-delivery',
    text: 'Swiggy One membership has become a massive scam. They advertised "Free Deliveries on all orders above ₹149." But now, for almost all popular restaurants, they have added a new "Rain Surge" or "High Demand Fee" of ₹30-50, which is not waived off under Swiggy One. They have basically renamed the delivery charge to bypass the membership agreement. Misleading marketing under ASCI guidelines. Paid ₹899 for this membership.',
    date: 'May 21, 2026',
    likes: 5400,
    shares: 2700,
    comments: 780,
    meTooCount: 3400,
    sourceUrl: 'https://x.com/search?q=swiggy%20one%20surge%20fee%20scam&src=typed_query&f=live',
  },
  {
    id: 'sc-041',
    username: 'arun.hyd',
    displayName: 'Arun Srinivas',
    avatarColor: '#BF360C',
    platform: 'facebook',
    company: 'Swiggy',
    companyColor: '#FC8019',
    category: 'food-delivery',
    text: 'Swiggy Instamart delivered dairy packets expiring on the exact same day. When I raised a refund request, the customer agent refused cash reversal, instead forcing me to accept "Swiggy Money Credits." Under RBI regulations, merchant apps cannot force customers to keep refunds in proprietary closed-loop wallets instead of returning to the original source bank account. I want my ₹645 back in my bank, not trapped in their ecosystem.',
    date: 'May 21, 2026',
    likes: 3100,
    shares: 1500,
    comments: 420,
    meTooCount: 980,
    sourceUrl: 'https://www.consumercomplaints.in/swiggy-b151/',
  },

  // ═══════════════════════════════════════════════════════════
  //  TELECOM
  // ═══════════════════════════════════════════════════════════

  // ── AIRTEL ────────────────────────────────────────────────
  {
    id: 'sc-005',
    username: 'vikram_consumer',
    displayName: 'Vikram Singh',
    avatarColor: '#F44336',
    platform: 'twitter',
    company: 'Airtel',
    companyColor: '#ED1C24',
    category: 'telecom',
    text: '@airtelindia tariff hikes continue to outpace actual network quality. Since the early 2026 pricing updates, I am paying ₹749 for a plan that used to cost ₹579, yet network call drops in the middle of New Delhi have worsened. Calls drop every 3 minutes and the "5G unlimited" plan fluctuates constantly to E or 3G speeds. TRAI needs to link tariff approvals directly to verified service quality metrics.',
    date: 'May 21, 2026',
    likes: 5600,
    shares: 2800,
    comments: 890,
    meTooCount: 2100,
    sourceUrl: 'https://x.com/search?q=airtel%20auto%20deducted%20plan%20not%20subscribed&src=typed_query&f=live',
  },
  {
    id: 'sc-018',
    username: 'pooja.broadband',
    displayName: 'Pooja Malhotra',
    avatarColor: '#9C27B0',
    platform: 'facebook',
    company: 'Airtel',
    companyColor: '#ED1C24',
    category: 'telecom',
    text: 'Airtel Xstream Fiber speed issues are persistent. I pay for a 200 Mbps connection, but Speedtest logs consistently show only 15-20 Mbps during work hours. Technicians have visited 3 times, each time blaming the "local fiber splitter junction" and promising a fix within 24 hours. Nothing changes, yet the full bill of ₹1,179 is generated automatically. 4 months of paying for services I am not receiving. Raised docket with TRAI PG Portal.',
    date: 'May 21, 2026',
    likes: 3200,
    shares: 1500,
    comments: 445,
    meTooCount: 1800,
    sourceUrl: 'https://www.consumercomplaints.in/airtel-b107/',
  },

  // ── JIO ───────────────────────────────────────────────────
  {
    id: 'sc-033',
    username: 'manoj.jio',
    displayName: 'Manoj Tiwari',
    avatarColor: '#1565C0',
    platform: 'twitter',
    company: 'Jio',
    companyColor: '#0A3A7D',
    category: 'telecom',
    text: '@reliancejio collected ₹1,000 advanced booking deposit for JioAirFiber installation in my area, promising setup within 48 hours. It has been 2 weeks now, and no installation team has arrived. When I tried to cancel, the app states the deposit is "non-refundable, only adjustable against future bills." How can it be non-refundable when they failed to provide the service in the first place? This is illegal withholding of consumer funds.',
    date: 'May 21, 2026',
    likes: 4100,
    shares: 2000,
    comments: 620,
    meTooCount: 1560,
    sourceUrl: 'https://x.com/search?q=jio%20auto%20activated%20plan%20without%20consent&src=typed_query&f=live',
  },
  {
    id: 'sc-034',
    username: 'suresh.net',
    displayName: 'Suresh Pandey',
    avatarColor: '#0277BD',
    platform: 'facebook',
    company: 'Jio',
    companyColor: '#0A3A7D',
    category: 'telecom',
    text: 'JioFiber network outage has hit my entire locality in East Delhi for 4 consecutive days now. Working from home has become completely impossible, forcing me to buy expensive daily 4G packs. Customer support chatbot gives pre-recorded "restoration delayed" messages with fake completion times. Total lack of accountability from Jio. Under TRAI regulations, consumers are entitled to pro-rata rebates for service outages exceeding 24 hours.',
    date: 'May 21, 2026',
    likes: 2800,
    shares: 1200,
    comments: 390,
    meTooCount: 2200,
    sourceUrl: 'https://www.consumercomplaints.in/reliance-jio-b150/',
  },

  // ── VODAFONE-IDEA (Vi) ────────────────────────────────────
  {
    id: 'sc-035',
    username: 'anand.vi.user',
    displayName: 'Anand Sharma',
    avatarColor: '#D32F2F',
    platform: 'twitter',
    company: 'Vi (Vodafone-Idea)',
    companyColor: '#E60000',
    category: 'telecom',
    text: '@ViCustomerCare is deliberately delaying my Mobile Number Portability (MNP) request. I submitted my porting request to move to another operator because of persistent zero network coverage in my office, but Vi rejected the UPC code 3 times citing "invalid pending dues," despite my postpaid account having a zero balance. This is a clear violation of TRAI porting regulations designed to hold customers hostage to bad service.',
    date: 'May 21, 2026',
    likes: 3900,
    shares: 1800,
    comments: 560,
    meTooCount: 4200,
    sourceUrl: 'https://x.com/search?q=vodafone%20idea%20Vi%20network%20call%20drops&src=typed_query&f=live',
  },

  // ── BSNL ──────────────────────────────────────────────────
  {
    id: 'sc-036',
    username: 'rajesh.bsnl',
    displayName: 'Rajesh Nair',
    avatarColor: '#1B5E20',
    platform: 'facebook',
    company: 'BSNL',
    companyColor: '#00599C',
    category: 'telecom',
    text: 'BSNL Broadband and Landline have been completely dead for 45 days. Opened 4 online tickets, and each one was marked "resolved" by their backend staff without a single technician visiting my house or fixing the line. BSNL customer service is an absolute black hole. My 82-year-old father has no mobile signal inside the house and relies entirely on the landline. Gross deficiency in utility services.',
    date: 'May 21, 2026',
    likes: 4500,
    shares: 2200,
    comments: 780,
    meTooCount: 1900,
    sourceUrl: 'https://www.consumercomplaints.in/bsnl-b106/',
  },

  // ═══════════════════════════════════════════════════════════
  //  BANKING & FINANCE
  // ═══════════════════════════════════════════════════════════

  // ── HDFC BANK ─────────────────────────────────────────────
  {
    id: 'sc-006',
    username: 'sanjay.hdfc.issue',
    displayName: 'Sanjay Gupta',
    avatarColor: '#1565C0',
    platform: 'facebook',
    company: 'HDFC Bank',
    companyColor: '#004C8F',
    category: 'banking',
    text: 'HDFC Bank credit card department auto-debited ₹12,000 from my card for a "Group Term Insurance" product that I never consented to. When I demanded immediate reversal, the branch staff claimed I had "verbal confirmation" recorded on a tele-calling offer. I never agreed. Under RBI guidelines, any activation of unsolicited insurance or cards without clear written consent is a punishable offense. Disputed this with the RBI Ombudsman. Pre-policy fraud!',
    date: 'May 21, 2026',
    likes: 4300,
    shares: 2100,
    comments: 670,
    meTooCount: 1560,
    sourceUrl: 'https://x.com/search?q=hdfc%20insurance%20charged%20credit%20card%20without%20consent&src=typed_query&f=live',
  },
  {
    id: 'sc-019',
    username: 'arjun.cards',
    displayName: 'Arjun Reddy',
    avatarColor: '#0D47A1',
    platform: 'twitter',
    company: 'HDFC Bank',
    companyColor: '#004C8F',
    category: 'banking',
    text: 'Unbelievable! @HDFC_Bank closed my active, zero-debt credit card without any email or SMS notice, citing an internal "inactive account optimization policy." This has caused a direct 40-point drop in my CIBIL score due to reduced credit availability, just when I am applying for a home loan. RBI guidelines clearly state banks must give at least 30 days written notice before closing credit cards. Escalated under the RBI Integrated Ombudsman Scheme (RB-IOS), 2026.',
    date: 'May 21, 2026',
    likes: 7800,
    shares: 3900,
    comments: 1100,
    meTooCount: 2300,
    sourceUrl: 'https://x.com/search?q=hdfc%20credit%20card%20closed%20cibil%20score%20dropped&src=typed_query&f=live',
  },

  // ── SBI ───────────────────────────────────────────────────
  {
    id: 'sc-037',
    username: 'kavitha.sbi',
    displayName: 'Kavitha Rajan',
    avatarColor: '#283593',
    platform: 'twitter',
    company: 'SBI',
    companyColor: '#22409A',
    category: 'banking',
    text: 'SBI ATM dispensed only ₹2,000 but debited my account for ₹10,000. I immediately filed a complaint at the branch and received a docket number, but the branch keeps telling me to wait "7-10 working days." It has been 25 days now, and they refuse to share the ATM transaction log or CCTV footage. RBI rules explicitly state banks must credit failed ATM transaction amounts back within 5 working days, or pay a penalty of ₹100/day. Demanding my money and late penalties.',
    date: 'May 21, 2026',
    likes: 5600,
    shares: 2800,
    comments: 890,
    meTooCount: 3400,
    sourceUrl: 'https://x.com/search?q=sbi%20atm%20debited%20not%20dispensed&src=typed_query&f=live',
  },
  {
    id: 'sc-038',
    username: 'gopal.pension',
    displayName: 'Gopal Krishna',
    avatarColor: '#1A237E',
    platform: 'facebook',
    company: 'SBI',
    companyColor: '#22409A',
    category: 'banking',
    text: 'My retired father\'s pension account at SBI was suddenly frozen without any notice due to pending "periodic KYC update." He has submitted his physical documents at the branch twice and completed video-KYC last month, yet their slow backend systems haven\'t updated his profile. He was unable to withdraw his pension for two months, causing extreme stress and delayed medical bill payments. This is harassment of senior citizens by public sector banks. Ombudsman notified.',
    date: 'May 21, 2026',
    likes: 6200,
    shares: 3100,
    comments: 980,
    meTooCount: 1200,
    sourceUrl: 'https://www.consumercomplaints.in/sbi-b104/',
  },

  // ── ICICI BANK ────────────────────────────────────────────
  {
    id: 'sc-039',
    username: 'nitin.loans',
    displayName: 'Nitin Agrawal',
    avatarColor: '#E65100',
    platform: 'twitter',
    company: 'ICICI Bank',
    companyColor: '#F58220',
    category: 'banking',
    text: 'Deceptive practice by @ICICIBank. I clicked a banner in their mobile app that said "Check eligibility for pre-approved personal loan." Without showing any final confirmation screens, interest breakdowns, or requiring an OTP, they immediately disbursed ₹3,00,000 into my savings account! When I called to cancel, they said I had to pay a "loan pre-closure charge" of 4% plus GST. This is forced debt dumping. RBI needs to ban single-click digital loan disbursals.',
    date: 'May 21, 2026',
    likes: 9200,
    shares: 4600,
    comments: 1400,
    meTooCount: 2800,
    sourceUrl: 'https://x.com/search?q=icici%20loan%20disbursed%20without%20consent&src=typed_query&f=live',
  },

  // ── PAYTM ─────────────────────────────────────────────────
  {
    id: 'sc-012',
    username: 'aditya.paytm',
    displayName: 'Aditya Mehta',
    avatarColor: '#00695C',
    platform: 'facebook',
    company: 'Paytm',
    companyColor: '#00BAF2',
    category: 'banking',
    text: 'My Paytm wallet account with ₹18,000 has been frozen due to "compliance updates required," but the app won\'t let me upload my documents, giving a continuous error. Customer support only responds with automated copy-paste answers about regulatory compliance. I cannot use my hard-earned money for weeks. Cyber crime portal complaints are filled with users facing similar lockouts. Give us access to our funds!',
    date: 'May 21, 2026',
    likes: 5100,
    shares: 2500,
    comments: 920,
    meTooCount: 1340,
    sourceUrl: 'https://x.com/search?q=paytm%20unauthorized%20transaction%20wallet&src=typed_query&f=live',
  },

  // ── PHONEPE ───────────────────────────────────────────────
  {
    id: 'sc-022',
    username: 'ramesh.upi',
    displayName: 'Ramesh Yadav',
    avatarColor: '#5C2D91',
    platform: 'twitter',
    company: 'PhonePe',
    companyColor: '#5F259F',
    category: 'banking',
    text: 'Extremely frustrated with @PhonePe. A high-value UPI transaction of ₹12,500 was debited from my SBI account but marked as "Pending" on the PhonePe app. The recipient never received it. PhonePe support claims the transaction is in "clearing stage" and will reverse in 5-7 days. It has been 12 days now, and the money is completely in limbo. Neither bank nor PhonePe takes ownership of digital payments stuck in the pipeline. Fix this!',
    date: 'May 21, 2026',
    likes: 4600,
    shares: 2300,
    comments: 670,
    meTooCount: 3200,
    sourceUrl: 'https://x.com/search?q=phonepe%20upi%20debited%20not%20credited&src=typed_query&f=live',
  },

  // ── CRED ──────────────────────────────────────────────────
  {
    id: 'sc-028',
    username: 'ritika.fintech',
    displayName: 'Ritika Saxena',
    avatarColor: '#263238',
    platform: 'twitter',
    company: 'CRED',
    companyColor: '#1C1C1C',
    category: 'banking',
    text: 'Zero accountability from @CRED_club. Paid my credit card bill of ₹24,000 through the CRED app. The amount was debited instantly from my bank account, but it took CRED 5 full days to credit the amount to my credit card. The credit card issuer charged me ₹850 in late fees and interest, and CRED customer service simply says "payment settlement partner issue, not our responsibility." They are advertising seamless instant bills, but we bear the penalty.',
    date: 'May 21, 2026',
    likes: 3800,
    shares: 1900,
    comments: 540,
    meTooCount: 920,
    sourceUrl: 'https://x.com/search?q=cred%20payment%20not%20credited%20credit%20card&src=typed_query&f=live',
  },

  // ═══════════════════════════════════════════════════════════
  //  INSURANCE
  // ═══════════════════════════════════════════════════════════

  // ── LIC ───────────────────────────────────────────────────
  {
    id: 'sc-008',
    username: 'ajay.insurance',
    displayName: 'Ajay Kumar',
    avatarColor: '#1B5E20',
    platform: 'facebook',
    company: 'LIC',
    companyColor: '#003D6B',
    category: 'insurance',
    text: 'LIC has delayed my father\'s maturity claim of over ₹4.5 lakh for 6 months. We have submitted the original policy bond, discharge form, and cancel cheque twice at the local branch, yet the staff keeps saying "file is pending regional office approval." This is classic government department red-tapism. My father needs this money for urgent medical treatments. IRDAI Bima Bharosa portal complaint has been filed.',
    date: 'May 21, 2026',
    likes: 6700,
    shares: 3400,
    comments: 890,
    meTooCount: 780,
    sourceUrl: 'https://www.consumercomplaints.in/lic-of-india-b103/',
  },

  // ── STAR HEALTH ───────────────────────────────────────────
  {
    id: 'sc-042',
    username: 'pradeep.health',
    displayName: 'Pradeep Sharma',
    avatarColor: '#2E7D32',
    platform: 'twitter',
    company: 'Star Health Insurance',
    companyColor: '#00A859',
    category: 'insurance',
    text: '@StarHealthIns rejected my wife\'s maternity hospitalization claim on the grounds of "pre-existing condition," despite the policy being continuously active and fully paid for over 3 years. How can a pregnancy that initiated 30 months after policy activation be considered a "pre-existing condition" at the time of purchase? This is an arbitrary, bad-faith rejection to avoid paying a ₹1.8 lakh hospital bill. Escalating to the IRDAI Ombudsman immediately.',
    date: 'May 21, 2026',
    likes: 7800,
    shares: 3900,
    comments: 1200,
    meTooCount: 1100,
    sourceUrl: 'https://x.com/search?q=star%20health%20claim%20rejected%20maternity&src=typed_query&f=live',
  },

  // ── BAJAJ ALLIANZ ─────────────────────────────────────────
  {
    id: 'sc-043',
    username: 'seema.claim',
    displayName: 'Seema Verma',
    avatarColor: '#4527A0',
    platform: 'facebook',
    company: 'Bajaj Allianz',
    companyColor: '#0066B3',
    category: 'insurance',
    text: 'Bajaj Allianz cashless motor insurance claim was rejected at the network workshop because the insurer\'s agreement with that specific garage had expired just 2 days prior. The garage was listed as an active network partner on the Bajaj Allianz portal when I met with the accident! I was forced to pay ₹1.5 lakh out of pocket. Now my reimbursement claim is pending with endless queries for over 90 days. Absolute lack of customer empathy.',
    date: 'May 21, 2026',
    likes: 4500,
    shares: 2200,
    comments: 680,
    meTooCount: 890,
    sourceUrl: 'https://www.consumercomplaints.in/bajaj-allianz-b134/',
  },

  // ── NEW INDIA ASSURANCE ───────────────────────────────────
  {
    id: 'sc-044',
    username: 'manoj.motor',
    displayName: 'Manoj Patel',
    avatarColor: '#0D47A1',
    platform: 'twitter',
    company: 'New India Assurance',
    companyColor: '#003366',
    category: 'insurance',
    text: 'Extremely slow service from @NewIndiaAssur. Filed an accidental damage claim for my car 3 months ago. The surveyor visited the workshop and completed the assessment, but the final repair approval has been delayed without any logical reason. The branch office says "the file is sent to the regional office for approval," and the regional office tells me to check with the branch. Classic PSU runaround while my car gathers dust in the workshop. NCH registered.',
    date: 'May 21, 2026',
    likes: 3200,
    shares: 1500,
    comments: 450,
    meTooCount: 670,
    sourceUrl: 'https://www.consumercomplaints.in/new-india-assurance-b160/',
  },

  // ═══════════════════════════════════════════════════════════
  //  UTILITIES
  // ═══════════════════════════════════════════════════════════

  // ── ELECTRICITY ───────────────────────────────────────────
  {
    id: 'sc-045',
    username: 'harish.power',
    displayName: 'Harish Bhat',
    avatarColor: '#E65100',
    platform: 'twitter',
    company: 'BESCOM (Bangalore)',
    companyColor: '#F57F17',
    category: 'utilities',
    text: 'Absolute shocker! My electricity bill from @BESCOM_Official jumped from the average ₹2,200/month to an astronomical ₹24,000 for May 2026, despite no changes in our household appliances or usage. Complained at the local sub-division office, and they flatly refused to check the meter, demanding I pay the full amount first to avoid disconnection. This is daylight robbery by public utilities. Filed an appeal with the Consumer Grievance Redressal Forum (CGRF).',
    date: 'May 21, 2026',
    likes: 5600,
    shares: 2800,
    comments: 890,
    meTooCount: 3200,
    sourceUrl: 'https://x.com/search?q=bescom%20electricity%20bill%20inflated%20wrong&src=typed_query&f=live',
  },
  {
    id: 'sc-046',
    username: 'sunita.power',
    displayName: 'Sunita Devi',
    avatarColor: '#BF360C',
    platform: 'facebook',
    company: 'BSES Delhi',
    companyColor: '#DC3545',
    category: 'utilities',
    text: 'BSES Rajdhani disconnected my power without giving the mandatory 15-day prior notice. They claim a pending arrear of ₹45,000, which belongs to a previous tenant of the flat who vacated 6 months ago! I have submitted the rent agreement, NOC, and all my monthly bills indicating zero dues, but their billing system has not updated. My senior citizen parents have been forced to live in the extreme heat without power for 3 days. Total high-handedness!',
    date: 'May 21, 2026',
    likes: 4200,
    shares: 2100,
    comments: 670,
    meTooCount: 1800,
    sourceUrl: 'https://www.consumercomplaints.in/bses-b159/',
  },

  // ── WATER ─────────────────────────────────────────────────
  {
    id: 'sc-047',
    username: 'anil.water',
    displayName: 'Anil Kumar',
    avatarColor: '#01579B',
    platform: 'facebook',
    company: 'Delhi Jal Board',
    companyColor: '#0277BD',
    category: 'utilities',
    text: 'Delhi Jal Board water bill of ₹18,000 generated on "assessment basis" for my 2BHK flat where only 2 people reside. The meter reader has not visited my house for over a year! When I filed a complaint at the DJB office, they said I have to hire a private plumber to verify the meter and get a certificate. Why should consumers bear the cost of certifying government-owned utility meters? Unresolved billing errors are getting out of hand.',
    date: 'May 21, 2026',
    likes: 3800,
    shares: 1800,
    comments: 540,
    meTooCount: 2100,
    sourceUrl: 'https://www.consumercomplaints.in/delhi-jal-board-b162/',
  },

  // ── GAS ───────────────────────────────────────────────────
  {
    id: 'sc-048',
    username: 'rekha.gas',
    displayName: 'Rekha Saxena',
    avatarColor: '#4E342E',
    platform: 'twitter',
    company: 'Indane Gas (IOCL)',
    companyColor: '#0C4DA2',
    category: 'utilities',
    text: 'It is 2026, and transferring an LPG gas connection to a new address in the same city still takes over 45 days. @IndaneGas local distributor refuses to deliver gas cylinders to my new residence, stating the "KYC address verification is pending approval from the regional office." My old address is just 3 km away! We have been forced to survive entirely on a single-induction cooktop for a month. Extremely backward public distribution systems.',
    date: 'May 21, 2026',
    likes: 2900,
    shares: 1400,
    comments: 380,
    meTooCount: 1500,
    sourceUrl: 'https://x.com/search?q=indane%20gas%20address%20change%20delay&src=typed_query&f=live',
  },

  // ── BROADBAND / ISP  ──────────────────────────────────────
  {
    id: 'sc-049',
    username: 'pankaj.isp',
    displayName: 'Pankaj Mishra',
    avatarColor: '#311B92',
    platform: 'twitter',
    company: 'ACT Fibernet',
    companyColor: '#E40046',
    category: 'utilities',
    text: 'Scam by @ACTFibernet. I purchased their 12-month advance rental plan for ₹12,000. Exactly 9 months into the plan, the internet connection was suspended, and the app showed "Plan Expired." When I uploaded the receipt showing a 12-month payment, support claimed the extra 3 months were a "promotional offer that has been revoked." This is a breach of contract. Filed a complaint on the national PG Portal for service fraud.',
    date: 'May 21, 2026',
    likes: 2600,
    shares: 1200,
    comments: 340,
    meTooCount: 780,
    sourceUrl: 'https://x.com/search?q=act%20fibernet%20annual%20plan%20stopped%20early&src=typed_query&f=live',
  },

  // ═══════════════════════════════════════════════════════════
  //  OTHER (Transport, Education, Electronics, Healthcare)
  // ═══════════════════════════════════════════════════════════

  // ── OLA ELECTRIC ──────────────────────────────────────────
  {
    id: 'sc-003',
    username: 'ankitmumbai',
    displayName: 'Ankit Patel',
    avatarColor: '#4CAF50',
    platform: 'twitter',
    company: 'Ola Electric',
    companyColor: '#1C8C3A',
    category: 'other',
    text: 'Despite @OlaElectric claiming in May 2026 that they have cleared 88% of their service backlogs, my S1 Pro scooter has been lying completely disassembled at their Mumbai service center for 60 days now. They have a massive shortage of battery control modules and BMS boards. No replacement vehicle has been provided and my bank EMI of ₹4,200 is still active for a vehicle I cannot ride. The service turnaround claims are completely manufactured for the media. NCH complaint filed.',
    date: 'May 21, 2026',
    likes: 8900,
    shares: 4200,
    comments: 1230,
    meTooCount: 3400,
    sourceUrl: 'https://x.com/search?q=ola%20electric%20service%20center%2045%20days&src=typed_query&f=live',
  },
  {
    id: 'sc-016',
    username: 'kiran.ev.user',
    displayName: 'Kiran Deshmukh',
    avatarColor: '#009688',
    platform: 'instagram',
    company: 'Ola Electric',
    companyColor: '#1C8C3A',
    category: 'other',
    text: 'A highly dangerous issue with my Ola S1. The battery display went from 70% to 0% within just 10 kilometers of riding, leaving me stranded in the middle of a flyover at night. The service center claims the battery pack does not have any physical defects and it is just a "software calibration issue." The software updates fix nothing. I feel completely cheated after paying ₹1.4 lakh. There are thousands of EV owners facing this identical BMS recalibration failure. CCPA must intervene.',
    date: 'May 21, 2026',
    likes: 12400,
    shares: 5600,
    comments: 1890,
    meTooCount: 4200,
    sourceUrl: 'https://x.com/search?q=ola%20electric%20battery%20drain%20complaint&src=typed_query&f=live',
  },

  // ── UBER INDIA ────────────────────────────────────────────
  {
    id: 'sc-023',
    username: 'prashant.rides',
    displayName: 'Prashant Dubey',
    avatarColor: '#424242',
    platform: 'twitter',
    company: 'Uber India',
    companyColor: '#000000',
    category: 'other',
    text: 'Uber driver took a massive 25km detour on what should have been a standard 6km ride, claiming "traffic bypass," and the app auto-adjusted my bill to ₹900 instead of the original ₹250 estimate. I raised a support ticket showing the GPS path manipulation, and the automated Uber support offered a ridiculous ₹50 refund. This is an outright scam. Ride-hailing apps cannot arbitrarily hike prices based on driver-manipulated routes. Demanding a full fare adjustment.',
    date: 'May 21, 2026',
    likes: 5800,
    shares: 2900,
    comments: 890,
    meTooCount: 1450,
    sourceUrl: 'https://x.com/search?q=uber%20india%20detour%20overcharged&src=typed_query&f=live',
  },

  // ── BYJU'S ────────────────────────────────────────────────
  {
    id: 'sc-024',
    username: 'sunita.parent',
    displayName: 'Sunita Sharma',
    avatarColor: '#6A1B9A',
    platform: 'facebook',
    company: 'BYJU\'S',
    companyColor: '#7C22C5',
    category: 'other',
    text: 'Unethical sales tactics continue at BYJU\'S. A sales representative visited my 72-year-old mother\'s house and convinced her to purchase a 3-year tablet learning course for ₹45,000 for her grandson, claiming it was a government-approved scheme. We cancelled the subscription in writing within 24 hours (well inside their 15-day refund window), but they have completely ignored all emails and calls. A refund has been denied. District Consumer Disputes Redressal Commission case filed. Beware of these predatory schemes!',
    date: 'May 21, 2026',
    likes: 9200,
    shares: 4600,
    comments: 1400,
    meTooCount: 2800,
    sourceUrl: 'https://x.com/search?q=byjus%20door%20to%20door%20sales%20refund%20refused&src=typed_query&f=live',
  },

  // ── INDIGO AIRLINES ───────────────────────────────────────
  {
    id: 'sc-025',
    username: 'manish.travels',
    displayName: 'Manish Kapoor',
    avatarColor: '#1A237E',
    platform: 'twitter',
    company: 'IndiGo Airlines',
    companyColor: '#003876',
    category: 'other',
    text: 'Shocking experience with @IndiGo6E. Flight 6E-**** was cancelled just 3 hours before departure. No alternative flight, hotel accommodation, or meal vouchers were provided at the airport. They simply sent a generic text stating "Refund will be processed in 14 days." Under DGCA rules, cancellation of flights within 24 hours requires airlines to provide either alternative travel or full compensation + immediate refunds. I was forced to buy a last-minute ticket on another airline for ₹18,000. #IndiGoFail',
    date: 'May 21, 2026',
    likes: 6100,
    shares: 3000,
    comments: 920,
    meTooCount: 780,
    sourceUrl: 'https://x.com/search?q=indigo%20flight%20cancelled%20no%20compensation&src=typed_query&f=live',
  },

  // ── MAKEMYTRIP ────────────────────────────────────────────
  {
    id: 'sc-011',
    username: 'kavita.consumer',
    displayName: 'Kavita Joshi',
    avatarColor: '#D32F2F',
    platform: 'twitter',
    company: 'MakeMyTrip',
    companyColor: '#EE2E24',
    category: 'other',
    text: 'MMT booking failure! Booked a hotel in Shimla through MakeMyTrip and received a "Confirmed" voucher. On arriving at midnight with my family, the hotel manager denied the reservation, stating they had terminated their partnership with MMT due to pending payments 2 weeks ago! MMT app support was completely unreachable. I had to pay double the rate at another hotel. This is massive deficiency of service. NCH Grievance registered.',
    date: 'May 21, 2026',
    likes: 4500,
    shares: 2200,
    comments: 780,
    meTooCount: 560,
    sourceUrl: 'https://x.com/search?q=makemytrip%20hotel%20no%20reservation%20confirmed&src=typed_query&f=live',
  },

  // ── SAMSUNG INDIA ─────────────────────────────────────────
  {
    id: 'sc-032',
    username: 'nikhil.gadgets',
    displayName: 'Nikhil Jain',
    avatarColor: '#0D47A1',
    platform: 'twitter',
    company: 'Samsung India',
    companyColor: '#1428A0',
    category: 'other',
    text: 'My Galaxy S25 developed a thin green line down the center of the display with zero drops, liquid contact, or physical damage. The phone is just 5 months old! @SamsungIndia service center is refusing a free warranty repair, claiming any screen pixel failures are considered "unauthorized physical pressure" and demand ₹18,000 for a screen replacement. This is a well-documented manufacturing display issue and they are evading warranty obligations.',
    date: 'May 21, 2026',
    likes: 4200,
    shares: 2100,
    comments: 630,
    meTooCount: 980,
    sourceUrl: 'https://x.com/search?q=samsung%20screen%20cracked%20internally%20warranty%20refused&src=typed_query&f=live',
  },

  // ── BOAT ──────────────────────────────────────────────────
  {
    id: 'sc-029',
    username: 'varun.audio',
    displayName: 'Varun Sharma',
    avatarColor: '#B71C1C',
    platform: 'twitter',
    company: 'boAt',
    companyColor: '#FF0000',
    category: 'other',
    text: '@RockWithboAt earbuds stopped charging in the right ear exactly 3 months after purchase. Raised a warranty ticket and sent them to their service center. They returned the product back, rejecting the claim stating "liquid ingress/water damage detected." These earbuds have never been exposed to water! Their warranty claim rejections are completely fake and designed to avoid replacing defective components. A total waste of ₹2,999.',
    date: 'May 21, 2026',
    likes: 3100,
    shares: 1500,
    comments: 430,
    meTooCount: 1800,
    sourceUrl: 'https://x.com/search?q=boat%20earbuds%20warranty%20water%20damage%20refused&src=typed_query&f=live',
  },

  // ── PHARMEASY ─────────────────────────────────────────────
  {
    id: 'sc-030',
    username: 'anita.health',
    displayName: 'Anita Grover',
    avatarColor: '#2E7D32',
    platform: 'instagram',
    company: 'PharmEasy',
    companyColor: '#26A65C',
    category: 'other',
    text: 'Incredibly dangerous mix-up! PharmEasy delivered a completely different medication from my prescription. I ordered my mother\'s vital blood pressure pills, but received high-dosage diabetes tablets in the box instead. If I hadn\'t checked the chemical name before giving them to her, this could have been fatal. Their prescription verification process is clearly non-existent. Registered a complaint with the State Drug Inspector.',
    date: 'May 21, 2026',
    likes: 8900,
    shares: 4500,
    comments: 1200,
    meTooCount: 340,
    sourceUrl: 'https://www.consumercomplaints.in/pharmeasy-b168/',
  },

  // ── TATA MOTORS ───────────────────────────────────────────
  {
    id: 'sc-031',
    username: 'rajiv.auto',
    displayName: 'Rajiv Menon',
    avatarColor: '#283593',
    platform: 'facebook',
    company: 'Tata Motors',
    companyColor: '#1C3F94',
    category: 'other',
    text: 'Tata Punch EV battery degradation is shocking. After only 12 months of usage, the full-charge highway range has dropped from 300 km to under 160 km. The local dealer and service team refuse to replace the battery pack under warranty, claiming a "40% capacity drop is within normal EV degradation standards." That is a complete lie. Tata EV customer support has completely ignored my emails. ₹14 lakh car has become practically useless for travel.',
    date: 'May 21, 2026',
    likes: 5600,
    shares: 2800,
    comments: 870,
    meTooCount: 450,
    sourceUrl: 'https://www.consumercomplaints.in/tata-motors-b105/',
  },

  // ── RAPIDO ────────────────────────────────────────────────
  {
    id: 'sc-050',
    username: 'pooja.rides',
    displayName: 'Pooja Deshaney',
    avatarColor: '#FF6F00',
    platform: 'twitter',
    company: 'Rapido',
    companyColor: '#FFCE08',
    category: 'other',
    text: '@rapidoapp auto drivers in Hyderabad are accepting rides and then calling to demand ₹50-80 extra over the app fare. If you refuse, they cancel the ride. Today, I had 4 cancellations in a row, which immediately triggered an automatic "surge price" of ₹240 instead of the standard ₹90 fare. This is manufactured artificial scarcity! The transport department needs to fine these aggregators for unchecked surge exploitation.',
    date: 'May 21, 2026',
    likes: 4100,
    shares: 2000,
    comments: 560,
    meTooCount: 3400,
    sourceUrl: 'https://x.com/search?q=rapido%20driver%20cancel%20surge%20pricing&src=typed_query&f=live',
  },

  // ── LENSKART ──────────────────────────────────────────────
  {
    id: 'sc-051',
    username: 'vivek.specs',
    displayName: 'Vivek Bansal',
    avatarColor: '#00695C',
    platform: 'instagram',
    company: 'Lenskart',
    companyColor: '#00BAC6',
    category: 'other',
    text: 'Lenskart delivered my progressive eyeglasses with the lens prescriptions swapped! The left eye power was put into the right side and vice versa. I suffered severe headaches and nausea for two weeks before getting them checked by an independent optometrist. When reported, Lenskart refused a refund, only offering a "free replacement" which takes another 10 days. Their quality checks are completely failing. Unacceptable!',
    date: 'May 21, 2026',
    likes: 3400,
    shares: 1600,
    comments: 480,
    meTooCount: 670,
    sourceUrl: 'https://www.consumercomplaints.in/lenskart-b157/',
  },

  // ── URBAN COMPANY ─────────────────────────────────────────
  {
    id: 'sc-052',
    username: 'meghna.service',
    displayName: 'Meghna Iyer',
    avatarColor: '#6A1B9A',
    platform: 'twitter',
    company: 'Urban Company',
    companyColor: '#6C3EC1',
    category: 'other',
    text: 'Deplorable service from @urbancompany_in. The AC service technician they sent damaged my refrigerator compressor line while moving the ladder during servicing. Now my fridge has completely stopped working and Urban Company customer support is refusing to pay for the repair costs, claiming "no proof that the damage occurred during our session." The fridge was fully functional before they arrived. Extremely expensive utility damage.',
    date: 'May 21, 2026',
    likes: 5200,
    shares: 2600,
    comments: 780,
    meTooCount: 1100,
    sourceUrl: 'https://x.com/search?q=urban%20company%20damaged%20ac%20during%20service&src=typed_query&f=live',
  },
];
